//
// Generated by JAXB
// Generated on: 2017.07.18 at 11:39:48 AM CEST 
//

package com.tieto.wro.java.a17.wunderground.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;

@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = { "version", "termsofService", "features", "error", "results", "currentObservation" })
@XmlRootElement(name = "response")
public class Response {

	protected String version;
	@XmlElement(required = true)
	protected String termsofService;
	@XmlElement(required = true)
	protected Response.Features features;
	@XmlElement(required = false)
	protected Response.Error error;
	@XmlElement(required = false)
	protected Response.Results results;
	@XmlElement(name = "current_observation", required = false)
	protected Response.CurrentObservation currentObservation;

	public String getVersion() {
		return version;
	}

	public void setVersion(String value) {
		this.version = value;
	}

	public String getTermsofService() {
		return termsofService;
	}

	public void setTermsofService(String value) {
		this.termsofService = value;
	}

	public Response.Features getFeatures() {
		return features;
	}

	public void setFeatures(Response.Features value) {
		this.features = value;
	}

	public Response.Error getError() {
		return error;
	}

	public void setError(Response.Error value) {
		this.error = value;
	}

	public Response.Results getResults() {
		return results;
	}

	public void setResults(Response.Results value) {
		this.results = value;
	}

	public Response.CurrentObservation getCurrentObservation() {
		return currentObservation;
	}

	public void setCurrentObservation(Response.CurrentObservation value) {
		this.currentObservation = value;
	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "type", "description" })
	public static class Error {

		@XmlElement(required = true)
		protected String type;
		@XmlElement(required = true)
		protected String description;

		public String getType() {
			return type;
		}

		public void setType(String value) {
			this.type = value;
		}

		public String getDescription() {
			return description;
		}

		public void setDescription(String value) {
			this.description = value;
		}

	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "feature" })
	public static class Features {

		@XmlElement(required = true)
		protected String feature;

		public String getFeature() {
			return feature;
		}

		public void setFeature(String value) {
			this.feature = value;
		}

	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "result" })
	public static class Results {

		protected List<Response.Results.Result> result;

		public List<Response.Results.Result> getResult() {
			if (result == null) {
				result = new ArrayList<Response.Results.Result>();
			}
			return this.result;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "name", "city", "state", "country", "countryIso3166", "countryName", "zmw",
				"l" })
		public static class Result {

			@XmlElement(required = true)
			protected String name;
			@XmlElement(required = true)
			protected String city;
			@XmlElement(required = true)
			protected String state;
			@XmlElement(required = true)
			protected String country;
			@XmlElement(name = "country_iso3166", required = true)
			protected String countryIso3166;
			@XmlElement(name = "country_name", required = true)
			protected String countryName;
			@XmlElement(required = true)
			protected String zmw;
			@XmlElement(required = true)
			protected String l;

			public String getName() {
				return name;
			}

			public void setName(String value) {
				this.name = value;
			}

			public String getCity() {
				return city;
			}

			public void setCity(String value) {
				this.city = value;
			}

			public String getState() {
				return state;
			}

			public void setState(String value) {
				this.state = value;
			}

			public String getCountry() {
				return country;
			}

			public void setCountry(String value) {
				this.country = value;
			}

			public String getCountryIso3166() {
				return countryIso3166;
			}

			public void setCountryIso3166(String value) {
				this.countryIso3166 = value;
			}

			public String getCountryName() {
				return countryName;
			}

			public void setCountryName(String value) {
				this.countryName = value;
			}

			public String getZmw() {
				return zmw;
			}

			public void setZmw(String value) {
				this.zmw = value;
			}

			public String getL() {
				return l;
			}

			public void setL(String value) {
				this.l = value;
			}

		}
	}

	@XmlAccessorType(XmlAccessType.FIELD)
	@XmlType(name = "", propOrder = { "image", "displayLocation", "observationLocation", "estimated", "stationId",
			"observationTime", "observationTimeRfc822", "observationEpoch", "localTimeRfc822", "localEpoch",
			"localTzString", "localTzLong", "localTzOffset", "weather", "temperatureString", "tempF", "tempC",
			"relativeHumidity", "windString", "windDir", "windDegrees", "windMph", "windGustMph", "windKph",
			"windGustKph", "pressureMb", "pressureIn", "pressureTrend", "dewpointString", "dewpointF", "dewpointC",
			"heatIndexString", "heatIndexF", "heatIndexC", "windchillString", "windchillF", "windchillC",
			"feelslikeString", "feelslikeF", "feelslikeC", "visibilityMi", "visibilityKm", "solarradiation", "uv",
			"precip1HrString", "precip1HrIn", "precip1HrMetric", "precipTodayString", "precipTodayIn",
			"precipTodayMetric", "icon", "iconUrl", "forecastUrl", "historyUrl", "obUrl" })
	public static class CurrentObservation {

		@XmlElement(required = true)
		protected Response.CurrentObservation.Image image;
		@XmlElement(name = "display_location", required = true)
		protected Response.CurrentObservation.DisplayLocation displayLocation;
		@XmlElement(name = "observation_location", required = true)
		protected Response.CurrentObservation.ObservationLocation observationLocation;
		@XmlElement(required = true)
		protected String estimated;
		@XmlElement(name = "station_id", required = true)
		protected String stationId;
		@XmlElement(name = "observation_time", required = true)
		protected String observationTime;
		@XmlElement(name = "observation_time_rfc822", required = true)
		protected String observationTimeRfc822;
		@XmlElement(name = "observation_epoch")
		protected String observationEpoch;
		@XmlElement(name = "local_time_rfc822", required = true)
		protected String localTimeRfc822;
		@XmlElement(name = "local_epoch")
		protected String localEpoch;
		@XmlElement(name = "local_tz_String", required = true)
		protected String localTzString;
		@XmlElement(name = "local_tz_long", required = true)
		protected String localTzLong;
		@XmlElement(name = "local_tz_offset")
		protected String localTzOffset;
		@XmlElement(required = true)
		protected String weather;
		@XmlElement(name = "temperature_string", required = true)
		protected String temperatureString;
		@XmlElement(name = "temp_f")
		protected String tempF;
		@XmlElement(name = "temp_c")
		protected String tempC;
		@XmlElement(name = "relative_humidity", required = true)
		protected String relativeHumidity;
		@XmlElement(name = "wind_string", required = true)
		protected String windString;
		@XmlElement(name = "wind_dir", required = true)
		protected String windDir;
		@XmlElement(name = "wind_degrees")
		protected String windDegrees;
		@XmlElement(name = "wind_mph")
		protected String windMph;
		@XmlElement(name = "wind_gust_mph")
		protected String windGustMph;
		@XmlElement(name = "wind_kph")
		protected String windKph;
		@XmlElement(name = "wind_gust_kph")
		protected String windGustKph;
		@XmlElement(name = "pressure_mb")
		protected String pressureMb;
		@XmlElement(name = "pressure_in")
		protected String pressureIn;
		@XmlElement(name = "pressure_trend")
		protected String pressureTrend;
		@XmlElement(name = "dewpoint_string", required = true)
		protected String dewpointString;
		@XmlElement(name = "dewpoint_f")
		protected String dewpointF;
		@XmlElement(name = "dewpoint_c")
		protected String dewpointC;
		@XmlElement(name = "heat_index_string", required = true)
		protected String heatIndexString;
		@XmlElement(name = "heat_index_f", required = true)
		protected String heatIndexF;
		@XmlElement(name = "heat_index_c", required = true)
		protected String heatIndexC;
		@XmlElement(name = "windchill_string", required = true)
		protected String windchillString;
		@XmlElement(name = "windchill_f", required = true)
		protected String windchillF;
		@XmlElement(name = "windchill_c", required = true)
		protected String windchillC;
		@XmlElement(name = "feelslike_string", required = true)
		protected String feelslikeString;
		@XmlElement(name = "feelslike_f")
		protected String feelslikeF;
		@XmlElement(name = "feelslike_c")
		protected String feelslikeC;
		@XmlElement(name = "visibility_mi", required = true)
		protected String visibilityMi;
		@XmlElement(name = "visibility_km", required = true)
		protected String visibilityKm;
		@XmlElement(required = true)
		protected String solarradiation;
		@XmlElement(name = "UV")
		protected String uv;
		@XmlElement(name = "precip_1hr_string", required = true)
		protected String precip1HrString;
		@XmlElement(name = "precip_1hr_in")
		protected String precip1HrIn;
		@XmlElement(name = "precip_1hr_metric")
		protected String precip1HrMetric;
		@XmlElement(name = "precip_today_string", required = true)
		protected String precipTodayString;
		@XmlElement(name = "precip_today_in")
		protected String precipTodayIn;
		@XmlElement(name = "precip_today_metric")
		protected String precipTodayMetric;
		@XmlElement(required = true)
		protected String icon;
		@XmlElement(name = "icon_url", required = true)
		@XmlSchemaType(name = "anyURI")
		protected String iconUrl;
		@XmlElement(name = "forecast_url", required = true)
		protected String forecastUrl;
		@XmlElement(name = "history_url", required = true)
		protected String historyUrl;
		@XmlElement(name = "ob_url", required = true)
		protected String obUrl;

		public Response.CurrentObservation.Image getImage() {
			return image;
		}

		public void setImage(Response.CurrentObservation.Image value) {
			this.image = value;
		}

		public Response.CurrentObservation.DisplayLocation getDisplayLocation() {
			return displayLocation;
		}

		public void setDisplayLocation(Response.CurrentObservation.DisplayLocation value) {
			this.displayLocation = value;
		}

		public Response.CurrentObservation.ObservationLocation getObservationLocation() {
			return observationLocation;
		}

		public void setObservationLocation(Response.CurrentObservation.ObservationLocation value) {
			this.observationLocation = value;
		}

		public String getEstimated() {
			return estimated;
		}

		public void setEstimated(String value) {
			this.estimated = value;
		}

		public String getStationId() {
			return stationId;
		}

		public void setStationId(String value) {
			this.stationId = value;
		}

		public String getObservationTime() {
			return observationTime;
		}

		public void setObservationTime(String value) {
			this.observationTime = value;
		}

		public String getObservationTimeRfc822() {
			return observationTimeRfc822;
		}

		public void setObservationTimeRfc822(String value) {
			this.observationTimeRfc822 = value;
		}

		public String getObservationEpoch() {
			return observationEpoch;
		}

		public void setObservationEpoch(String value) {
			this.observationEpoch = value;
		}

		public String getLocalTimeRfc822() {
			return localTimeRfc822;
		}

		public void setLocalTimeRfc822(String value) {
			this.localTimeRfc822 = value;
		}

		public String getLocalEpoch() {
			return localEpoch;
		}

		public void setLocalEpoch(String value) {
			this.localEpoch = value;
		}

		public String getLocalTzString() {
			return localTzString;
		}

		public void setLocalTzString(String value) {
			this.localTzString = value;
		}

		public String getLocalTzLong() {
			return localTzLong;
		}

		public void setLocalTzLong(String value) {
			this.localTzLong = value;
		}

		public String getLocalTzOffset() {
			return localTzOffset;
		}

		public void setLocalTzOffset(String value) {
			this.localTzOffset = value;
		}

		public String getWeather() {
			return weather;
		}

		public void setWeather(String value) {
			this.weather = value;
		}

		public String getTemperatureString() {
			return temperatureString;
		}

		public void setTemperatureString(String value) {
			this.temperatureString = value;
		}

		public String getTempF() {
			return tempF;
		}

		public void setTempF(String value) {
			this.tempF = value;
		}

		public String getTempC() {
			return tempC;
		}

		public void setTempC(String value) {
			this.tempC = value;
		}

		public String getRelativeHumidity() {
			return relativeHumidity;
		}

		public void setRelativeHumidity(String value) {
			this.relativeHumidity = value;
		}

		public String getWindString() {
			return windString;
		}

		public void setWindString(String value) {
			this.windString = value;
		}

		public String getWindDir() {
			return windDir;
		}

		public void setWindDir(String value) {
			this.windDir = value;
		}

		public String getWindDegrees() {
			return windDegrees;
		}

		public void setWindDegrees(String value) {
			this.windDegrees = value;
		}

		public String getWindMph() {
			return windMph;
		}

		public void setWindMph(String value) {
			this.windMph = value;
		}

		public String getWindGustMph() {
			return windGustMph;
		}

		public void setWindGustMph(String value) {
			this.windGustMph = value;
		}

		public String getWindKph() {
			return windKph;
		}

		public void setWindKph(String value) {
			this.windKph = value;
		}

		public String getWindGustKph() {
			return windGustKph;
		}

		public void setWindGustKph(String value) {
			this.windGustKph = value;
		}

		public String getPressureMb() {
			return pressureMb;
		}

		public void setPressureMb(String value) {
			this.pressureMb = value;
		}

		public String getPressureIn() {
			return pressureIn;
		}

		public void setPressureIn(String value) {
			this.pressureIn = value;
		}

		public String getPressureTrend() {
			return pressureTrend;
		}

		public void setPressureTrend(String value) {
			this.pressureTrend = value;
		}

		public String getDewpointString() {
			return dewpointString;
		}

		public void setDewpointString(String value) {
			this.dewpointString = value;
		}

		public String getDewpointF() {
			return dewpointF;
		}

		public void setDewpointF(String value) {
			this.dewpointF = value;
		}

		public String getDewpointC() {
			return dewpointC;
		}

		public void setDewpointC(String value) {
			this.dewpointC = value;
		}

		public String getHeatIndexString() {
			return heatIndexString;
		}

		public void setHeatIndexString(String value) {
			this.heatIndexString = value;
		}

		public String getHeatIndexF() {
			return heatIndexF;
		}

		public void setHeatIndexF(String value) {
			this.heatIndexF = value;
		}

		public String getHeatIndexC() {
			return heatIndexC;
		}

		public void setHeatIndexC(String value) {
			this.heatIndexC = value;
		}

		public String getWindchillString() {
			return windchillString;
		}

		public void setWindchillString(String value) {
			this.windchillString = value;
		}

		public String getWindchillF() {
			return windchillF;
		}

		public void setWindchillF(String value) {
			this.windchillF = value;
		}

		public String getWindchillC() {
			return windchillC;
		}

		public void setWindchillC(String value) {
			this.windchillC = value;
		}

		public String getFeelslikeString() {
			return feelslikeString;
		}

		public void setFeelslikeString(String value) {
			this.feelslikeString = value;
		}

		public String getFeelslikeF() {
			return feelslikeF;
		}

		public void setFeelslikeF(String value) {
			this.feelslikeF = value;
		}

		public String getFeelslikeC() {
			return feelslikeC;
		}

		public void setFeelslikeC(String value) {
			this.feelslikeC = value;
		}

		public String getVisibilityMi() {
			return visibilityMi;
		}

		public void setVisibilityMi(String value) {
			this.visibilityMi = value;
		}

		public String getVisibilityKm() {
			return visibilityKm;
		}

		public void setVisibilityKm(String value) {
			this.visibilityKm = value;
		}

		public String getSolarradiation() {
			return solarradiation;
		}

		public void setSolarradiation(String value) {
			this.solarradiation = value;
		}

		public String getUV() {
			return uv;
		}

		public void setUV(String value) {
			this.uv = value;
		}

		public String getPrecip1HrString() {
			return precip1HrString;
		}

		public void setPrecip1HrString(String value) {
			this.precip1HrString = value;
		}

		public String getPrecip1HrIn() {
			return precip1HrIn;
		}

		public void setPrecip1HrIn(String value) {
			this.precip1HrIn = value;
		}

		public String getPrecip1HrMetric() {
			return precip1HrMetric;
		}

		public void setPrecip1HrMetric(String value) {
			this.precip1HrMetric = value;
		}

		public String getPrecipTodayString() {
			return precipTodayString;
		}

		public void setPrecipTodayString(String value) {
			this.precipTodayString = value;
		}

		public String getPrecipTodayIn() {
			return precipTodayIn;
		}

		public void setPrecipTodayIn(String value) {
			this.precipTodayIn = value;
		}

		public String getPrecipTodayMetric() {
			return precipTodayMetric;
		}

		public void setPrecipTodayMetric(String value) {
			this.precipTodayMetric = value;
		}

		public String getIcon() {
			return icon;
		}

		public void setIcon(String value) {
			this.icon = value;
		}

		public String getIconUrl() {
			return iconUrl;
		}

		public void setIconUrl(String value) {
			this.iconUrl = value;
		}

		public String getForecastUrl() {
			return forecastUrl;
		}

		public void setForecastUrl(String value) {
			this.forecastUrl = value;
		}

		public String getHistoryUrl() {
			return historyUrl;
		}

		public void setHistoryUrl(String value) {
			this.historyUrl = value;
		}

		public String getObUrl() {
			return obUrl;
		}

		public void setObUrl(String value) {
			this.obUrl = value;
		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "full", "city", "state", "stateName", "country", "countryIso3166", "zip",
				"magic", "wmo", "latitude", "longitude", "elevation" })
		public static class DisplayLocation {

			@XmlElement(required = true)
			protected String full;
			@XmlElement(required = true)
			protected String city;
			@XmlElement(required = true)
			protected String state;
			@XmlElement(name = "state_name", required = true)
			protected String stateName;
			@XmlElement(required = true)
			protected String country;
			@XmlElement(name = "country_iso3166", required = true)
			protected String countryIso3166;
			protected String zip;
			protected String magic;
			protected String wmo;
			protected String latitude;
			protected String longitude;
			protected String elevation;

			public String getFull() {
				return full;
			}

			public void setFull(String value) {
				this.full = value;
			}

			public String getCity() {
				return city;
			}

			public void setCity(String value) {
				this.city = value;
			}

			public String getState() {
				return state;
			}

			public void setState(String value) {
				this.state = value;
			}

			public String getStateName() {
				return stateName;
			}

			public void setStateName(String value) {
				this.stateName = value;
			}

			public String getCountry() {
				return country;
			}

			public void setCountry(String value) {
				this.country = value;
			}

			public String getCountryIso3166() {
				return countryIso3166;
			}

			public void setCountryIso3166(String value) {
				this.countryIso3166 = value;
			}

			public String getZip() {
				return zip;
			}

			public void setZip(String value) {
				this.zip = value;
			}

			public String getMagic() {
				return magic;
			}

			public void setMagic(String value) {
				this.magic = value;
			}

			public String getWmo() {
				return wmo;
			}

			public void setWmo(String value) {
				this.wmo = value;
			}

			public String getLatitude() {
				return latitude;
			}

			public void setLatitude(String value) {
				this.latitude = value;
			}

			public String getLongitude() {
				return longitude;
			}

			public void setLongitude(String value) {
				this.longitude = value;
			}

			public String getElevation() {
				return elevation;
			}

			public void setElevation(String value) {
				this.elevation = value;
			}

		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "url", "title", "link" })
		public static class Image {

			@XmlElement(required = true)
			@XmlSchemaType(name = "anyURI")
			protected String url;
			@XmlElement(required = true)
			protected String title;
			@XmlElement(required = true)
			@XmlSchemaType(name = "anyURI")
			protected String link;

			public String getUrl() {
				return url;
			}

			public void setUrl(String value) {
				this.url = value;
			}

			public String getTitle() {
				return title;
			}

			public void setTitle(String value) {
				this.title = value;
			}

			public String getLink() {
				return link;
			}

			public void setLink(String value) {
				this.link = value;
			}

		}

		@XmlAccessorType(XmlAccessType.FIELD)
		@XmlType(name = "", propOrder = { "full", "city", "state", "country", "countryIso3166", "latitude", "longitude",
				"elevation" })
		public static class ObservationLocation {

			@XmlElement(required = true)
			protected String full;
			@XmlElement(required = true)
			protected String city;
			@XmlElement(required = true)
			protected String state;
			@XmlElement(required = true)
			protected String country;
			@XmlElement(name = "country_iso3166", required = true)
			protected String countryIso3166;
			protected String latitude;
			protected String longitude;
			@XmlElement(required = true)
			protected String elevation;

			public String getFull() {
				return full;
			}

			public void setFull(String value) {
				this.full = value;
			}

			public String getCity() {
				return city;
			}

			public void setCity(String value) {
				this.city = value;
			}

			public String getState() {
				return state;
			}

			public void setState(String value) {
				this.state = value;
			}

			public String getCountry() {
				return country;
			}

			public void setCountry(String value) {
				this.country = value;
			}

			public String getCountryIso3166() {
				return countryIso3166;
			}

			public void setCountryIso3166(String value) {
				this.countryIso3166 = value;
			}

			public String getLatitude() {
				return latitude;
			}

			public void setLatitude(String value) {
				this.latitude = value;
			}

			public String getLongitude() {
				return longitude;
			}

			public void setLongitude(String value) {
				this.longitude = value;
			}

			public String getElevation() {
				return elevation;
			}

			public void setElevation(String value) {
				this.elevation = value;
			}

		}

	}

}
